### ISSUE TITLE
Question: How can I retrieve an enum member by value?

### ISSUE THREAD

**Issue by ezzatron** [adrai/enum#3]
Say for example I have this enum:

``` js
var Members = new Enum({
  A: "a",
  B: "b"
});
```

I'd like to be able to do something like:

``` js
var member = Members.byValue('a');
```

Did I miss something in the documentation, or is this currently impossible?

**Comment by ColinRhodes** [comment]
What is the reason for not allowing strings as values?  I see this as a pretty common use case.  In my system, use strings as values so that they are human-readable in the database.  This means that in addition to wanting to use strings as values, I'd also be looking for an option to have a constructor option that changes the behaviour of toString/toJSON to return the value rather than the key.

**Comment by adrai** [comment]
Try to do a pull request...
